-- Migration script to change ID columns from BIGINT to VARCHAR(36) for UUID

-- WARNING: This will delete all existing data!
-- Make sure to backup your data before running this script

-- Drop foreign key constraints first
ALTER TABLE DOCUMENTS DROP FOREIGN KEY IF EXISTS fk_documents__owner_id;
ALTER TABLE DOCUMENT_SHARES DROP FOREIGN KEY IF EXISTS fk_document_shares__document_id;
ALTER TABLE DOCUMENT_SHARES DROP FOREIGN KEY IF EXISTS fk_document_shares__user_id;
ALTER TABLE SENSITIVE_INFO DROP FOREIGN KEY IF EXISTS fk_sensitive_info__document_id;
ALTER TABLE AUDIT_LOGS DROP FOREIGN KEY IF EXISTS fk_audit_logs__user_id;
ALTER TABLE AUDIT_LOGS DROP FOREIGN KEY IF EXISTS fk_audit_logs__document_id;

-- Drop and recreate tables with UUID primary keys

-- USERS table (AppUser)
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at DATETIME(6),
    updated_at DATETIME(6)
);

-- DOCUMENTS table
DROP TABLE IF EXISTS DOCUMENTS;
CREATE TABLE DOCUMENTS (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    storage_path TEXT NOT NULL,
    uploaded_at DATETIME(6),
    owner_id VARCHAR(36) NOT NULL
);

-- SENSITIVE_INFO table
DROP TABLE IF EXISTS SENSITIVE_INFO;
CREATE TABLE SENSITIVE_INFO (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    info_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    page_number INT,
    position VARCHAR(255),
    detected_at DATETIME(6),
    document_id VARCHAR(36) NOT NULL
);

-- DOCUMENT_SHARES table
DROP TABLE IF EXISTS DOCUMENT_SHARES;
CREATE TABLE DOCUMENT_SHARES (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    permission VARCHAR(50) NOT NULL,
    granted_at DATETIME(6),
    document_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL
);

-- AUDIT_LOGS table
DROP TABLE IF EXISTS AUDIT_LOGS;
CREATE TABLE AUDIT_LOGS (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    detail TEXT,
    created_at DATETIME(6),
    user_id VARCHAR(36) NOT NULL,
    document_id VARCHAR(36)
);

-- Add foreign key constraints back
ALTER TABLE DOCUMENTS ADD CONSTRAINT fk_documents__owner_id 
    FOREIGN KEY (owner_id) REFERENCES USERS(id);

ALTER TABLE DOCUMENT_SHARES ADD CONSTRAINT fk_document_shares__document_id 
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(id);

ALTER TABLE DOCUMENT_SHARES ADD CONSTRAINT fk_document_shares__user_id 
    FOREIGN KEY (user_id) REFERENCES USERS(id);

ALTER TABLE SENSITIVE_INFO ADD CONSTRAINT fk_sensitive_info__document_id 
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(id);

ALTER TABLE AUDIT_LOGS ADD CONSTRAINT fk_audit_logs__user_id 
    FOREIGN KEY (user_id) REFERENCES USERS(id);

ALTER TABLE AUDIT_LOGS ADD CONSTRAINT fk_audit_logs__document_id 
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(id);

-- Insert a test user (UUID will be generated by application)
-- INSERT INTO USERS (id, full_name, email, password_hash, role, created_at, updated_at) 
-- VALUES ('550e8400-e29b-41d4-a716-446655440000', 'Test User', 'test@example.com', '$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vFnbbqFbkqVE6', 'user', NOW(), NOW());

SELECT 'Migration completed successfully!' as status;
