package com.mbbank.biz.pro.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentShareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentShareAllPropertiesEquals(DocumentShare expected, DocumentShare actual) {
        assertDocumentShareAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentShareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentShareAllUpdatablePropertiesEquals(DocumentShare expected, DocumentShare actual) {
        assertDocumentShareUpdatableFieldsEquals(expected, actual);
        assertDocumentShareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentShareAutoGeneratedPropertiesEquals(DocumentShare expected, DocumentShare actual) {
        assertThat(actual)
            .as("Verify DocumentShare auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentShareUpdatableFieldsEquals(DocumentShare expected, DocumentShare actual) {
        assertThat(actual)
            .as("Verify DocumentShare relevant properties")
            .satisfies(a -> assertThat(a.getPermission()).as("check permission").isEqualTo(expected.getPermission()))
            .satisfies(a -> assertThat(a.getGrantedAt()).as("check grantedAt").isEqualTo(expected.getGrantedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentShareUpdatableRelationshipsEquals(DocumentShare expected, DocumentShare actual) {
        assertThat(actual)
            .as("Verify DocumentShare relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
