package com.mbbank.biz.pro.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SensitiveInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensitiveInfoAllPropertiesEquals(SensitiveInfo expected, SensitiveInfo actual) {
        assertSensitiveInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertSensitiveInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensitiveInfoAllUpdatablePropertiesEquals(SensitiveInfo expected, SensitiveInfo actual) {
        assertSensitiveInfoUpdatableFieldsEquals(expected, actual);
        assertSensitiveInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensitiveInfoAutoGeneratedPropertiesEquals(SensitiveInfo expected, SensitiveInfo actual) {
        assertThat(actual)
            .as("Verify SensitiveInfo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensitiveInfoUpdatableFieldsEquals(SensitiveInfo expected, SensitiveInfo actual) {
        assertThat(actual)
            .as("Verify SensitiveInfo relevant properties")
            .satisfies(a -> assertThat(a.getInfoType()).as("check infoType").isEqualTo(expected.getInfoType()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getDetectedAt()).as("check detectedAt").isEqualTo(expected.getDetectedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensitiveInfoUpdatableRelationshipsEquals(SensitiveInfo expected, SensitiveInfo actual) {
        assertThat(actual)
            .as("Verify SensitiveInfo relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
